# Generated by Django 3.1.7 on 2021-03-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSystemManagment', '0002_admin_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolSystemManagment.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolSystemManagment.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudiesStudent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('finishedFlag', models.BooleanField(default=False)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolSystemManagment.student')),
                ('studyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolSystemManagment.studies')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSolution',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolSystemManagment.student')),
                ('teacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolSystemManagment.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolSystemManagment.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('homeWorkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolSystemManagment.homework')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolSystemManagment.student')),
            ],
        ),
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolSystemManagment.admin')),
            ],
        ),
    ]
