# Generated by Django 3.1.7 on 2021-04-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSystemManagment', '0003_adminmessage_grade_homework_studentsolution_studies_studiesstudent_teachermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='messageContent',
            field=models.TextField(default=''),
        ),
    ]
