# Generated by Django 3.1.7 on 2021-04-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSystemManagment', '0004_adminmessage_messagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacherComment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homework',
            name='homeWorkContent',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studentsolution',
            name='solutionContent',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studies',
            name='contentLink',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teachermessage',
            name='messageContent',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='adminId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schoolSystemManagment.admin'),
        ),
    ]
