  
pipeline {
    agent none
    stages {

        stage('Build') {
            agent {
                docker {
                    image 'amarhabneen/bm_team7'
                }
            }
            steps {
		    withEnv(["HOME=${env.WORKSPACE}"]) {
					
                sh 'python3 -m venv env'
		sh 'pip install -r requirements.txt'
					
		    }
            }

        }
      stage('Test') {
            agent {
                docker {
                    image 'amarhabneen/bm_team7'
                }
            }
            steps {
                sh 'python manage.py test'
            }

        }

    }
}
